#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0
rm -rf constant/htx/polyMesh
rm -rf constant/hydride/polyMesh

# ----------------------------------------------------------------- end-of-file
