#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in htx
do
   rm -f 0*/$i/{p,F}
done

for i in htx hydride
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

#-- Run on single processor
hydrideBedFoam

# Decompose
#for i in bottomWater topAir heater leftSolid rightSolid
#do
#   decomposePar -region $i > log.decomposePar.$i 2>&1
#done

# Run
#runParallel `getApplication` 4

# Reconstruct
#for i in bottomWater topAir heater leftSolid rightSolid
#do
#   reconstructPar -region $i > log.reconstructPar.$i 2>&1
#done


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
