#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
blockMesh
topoSet
subsetMesh -overwrite c0 -patch insulated

topoSet -dict system/topoSetDict2
subsetMesh -overwrite c1 -patch coldplate

topoSet -dict system/topoSetDict3
splitMeshRegions -cellZones -overwrite

rm -f 0/meshPhi*

# remove fluid fields from solid regions (important for post-processing)
for i in htx
do
   rm -f 0*/$i/{p*,F*}
done

for i in htx hydride
do
   changeDictionary -region $i
done

#-- Run on single processor
#hydrideBedFoam

# run in parallel

# Decompose
for i in htx hydride
do
   decomposePar -region $i
done

# Run
#runParallel `getApplication` 16
#mpirun -np 16 hydrideBedFoam -parallel
foamJob -screen -parallel hydrideBedFoam

# Reconstruct
for i in htx hydride
do
   reconstructPar -region $i
done


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

sample -time 0: -region htx
sample -time 0: -region hydride

python getPoints.py

# ----------------------------------------------------------------- end-of-file
